#!/usr/bin/python

# Cozy Backup Solution
# Copyright (C) 2009  Peter Goetz
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as published by
# the Free Software Foundation.
#  
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#    
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

import os
import sys

class ProgramPaths:
    pass

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

def is_system_wide_install():
    return not os.path.exists(os.path.join(BASE_DIR, 'lib'))

program_paths = ProgramPaths()

if is_system_wide_install():
    sys.path.append('/usr/lib/cozy')    
    program_paths.COZY_RESTORE_BACKEND_PATH = 'cozy-restore-backend'
    program_paths.COZY_BACKUP_APPLET_PATH = 'cozy-backup-applet'
    program_paths.COZY_BACKUP_PATH = 'cozy-backup'
else:
    sys.path.append(BASE_DIR)
    sys.path.append(os.path.join(BASE_DIR, 'lib'))
    os.environ['PATH'] += ':' + os.path.join(BASE_DIR, 'cozyfs')
    if os.environ.has_key('PYTHONPATH'):
        os.environ['PYTHONPATH'] = os.environ['PYTHONPATH'] + ':' + BASE_DIR
    else:
        os.environ['PYTHONPATH'] = BASE_DIR
    program_paths.COZY_RESTORE_BACKEND_PATH = os.path.join(BASE_DIR, 'cozy-restore-backend')
    program_paths.COZY_BACKUP_APPLET_PATH = os.path.join(BASE_DIR, 'cozy-backup-applet')
    program_paths.COZY_BACKUP_PATH = os.path.join(BASE_DIR, 'cozy-backup')
        


import cozy_setup

cozy_setup.main(program_paths)
